name: Test Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Run tests and package
      run: ./mvnw package

    - name: Publish JUnit test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: junit-test-results
        path: target/surefire-reports/*.xml   
        
        
    - name: Deploy App
      if: ${{ success() }}
      uses: ./.github/workflows/deploymaven.yml@v1
      with:
        workflow: deploymaven.yml
        token: ${{ secrets.GITHUB_TOKEN }}
